{
 "title": "Malachite Consensus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(malachitebft_core_consensus_height, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_connected_peers{}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_height",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Round",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_round",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Size of queue (heights)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_queue_heights",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Size of queue (total size)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "malachitebft_core_consensus_queue_size",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consensus time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(malachitebft_core_consensus_consensus_time_sum[$__rate_interval]) / rate(malachitebft_core_consensus_consensus_time_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Requests sent",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(malachitebft_sync_value_requests_sent_total[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Responses received",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "increase(malachitebft_sync_value_responses_received_total[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request timeouts",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(malachitebft_sync_value_request_timeouts_total[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sync latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(malachitebft_sync_value_client_latency_sum[$__rate_interval]) / rate(malachitebft_sync_value_client_latency_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Consensus - Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "P2P bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(malachitebft_network_libp2p_bandwidth_bytes_total[$__rate_interval])",
     "legendFormat": "{{job}} ({{direction}})"
    }
   ]
  },
  {
   "title": "GossipSub messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "rate(malachitebft_network_libp2p_gossipsub_messages_total[$__rate_interval])",
     "legendFormat": "{{job}} ({{direction}})"
    }
   ]
  },
  { "title": "Consensus - P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } }
 ]
}